### ISSUE TITLE
Add @tarynmusgrave to repository

### ISSUE THREAD

**Issue by ghost** [Ka-Ma/AssistiveComputing#1]
Hi :) I am deleting this account. Can you please add my other account as a collaborator to this repository. 

My username is tarynmusgrave :)

Thanks,
T

**Comment by CordellSmith** [comment]
Hey Tarryn,

I’m looking but can’t see the settings option. It may be because I’m not the owner of the repository, I think you might have to do it but not sure what will happen once your account is deleted.

Kind Regards,

Cordell Smith

On 3 Apr 2018, at 11:16 am, tarynnnnnnnnnnn <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi :) I am deleting this account. Can you please add my other account as a collaborator to this repository.

My username is tarynmusgrave :)

Thanks,
T

**Comment by Ka-Ma** [comment]
I have invited Taryn back into the fold.

**Comment by CordellSmith** [comment]
Oh my mistake, it was Katherine’s repository 😊

Kind Regards,

Cordell Smith

On 3 Apr 2018, at 11:38 am, Ka-Ma <notifications@github.com<mailto:notifications@github.com>> wrote:


I have invited Taryn back into the fold.
